### ISSUE TITLE
README examples don't work

### ISSUE THREAD

**Issue by privard** [mhssmnn/redux-form-saga#4]
I've tried to replicate the short example in the README, passing a string to createFormAction, but doing so results in redux-form dispatching a `redux-form/STOP-SUBMIT` action with the following error:

```
TypeError: requestAction is not a function
    at eval (eval at <anonymous> (http://0.0.0.0:3001/js/bundle.js:6692:2), <anonymous>:69:18)
    at eval (eval at <anonymous> (http://0.0.0.0:3001/js/bundle.js:6692:2), <anonymous>:66:12)
    at doSubmit (eval at <anonymous> (http://0.0.0.0:3001/js/bundle.js:6764:2), <anonymous>:31:20)
    at handleSubmit (eval at <anonymous> (http://0.0.0.0:3001/js/bundle.js:6764:2), <anonymous>:64:10)
    at eval (eval at <anonymous> (http://0.0.0.0:3001/js/bundle.js:6710:2), <anonymous>:190:45)
    at eval (eval at <anonymous> (http://0.0.0.0:3001/js/bundle.js:6758:2), <anonymous>:17:52)
    at Object.ReactErrorUtils.invokeGuardedCallback (eval at <anonymous> (http://0.0.0.0:3001/js/bundle.js:2144:2), <anonymous>:70:16)
    at executeDispatch (eval at <anonymous> (http://0.0.0.0:3001/js/bundle.js:2114:2), <anonymous>:89:21)
    at Object.executeDispatchesInOrder (eval at <anonymous> (http://0.0.0.0:3001/js/bundle.js:2114:2), <anonymous>:112:5)
    at executeDispatchesAndRelease (eval at <anonymous> (http://0.0.0.0:3001/js/bundle.js:1394:2), <anonymous>:44:22)
```

I believe this might be traceable to the way createFormAction returns its submit handler. By outputting the value of requestAction in the console, I can clearly see that `requestAction` is still a string in the handler. Hence the error.  

```
return Object.assign((data, dispatch) => {
    return new Promise((resolve, reject) => {
      dispatch(formAction({
        request: requestAction(data),
        defer: { resolve, reject },
        types
      }));
    });
  }, actionMethods);
```

Changing `requestAction(data)` to `actionMethods.request(data)` seems to solve the problem. Anyone else having this behaviour?

**Comment by mhssmnn** [comment]
@privard that's odd. I'm using the short version extensively, and it's passing tests. Can you post your code calling the `createFormAction` function?

**Comment by privard** [comment]
@mhssmnn I think the shorthand documentation has me confused. I followed the long version example and it worked fine. I was able to see all the dispatched actions with a logger. I was just basically doing what's in the README, so I'm pretty sure I'm missing something. Does `createFormAction` build the actions and action creators on its own in the shorthand version?

```javascript
import React from 'react'
import { reduxForm } from 'redux-form';
import classNames from 'classnames';
import { createFormAction } from 'redux-form-saga';

const typePrefix = 'LOGIN';
export const loginFormActions = createFormAction(typePrefix);

const validate = values => {
    const errors = {};

    if (!values.email) {
        errors.email = 'Required';
    } else if (!/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(values.email)) {
        errors.email = 'Invalid email address';
    }

    return errors;
}

class LoginForm extends React.Component {

    constructor(props) {
        super(props);
    }

    render() {
        const { fields: {email}, handleSubmit, error, submitting} = this.props;

        const emailClasses = classNames({
            'form-group': true,
            'has-error': email.touched && email.error
        });

        return (
            <form onSubmit={handleSubmit(loginFormActions)}>
                { error && <div className='alert alert-danger'>{error}</div> }

                <button className='btn btn-lg btn-block btn-primary'>Login with Facebook</button>

                <hr/>

                <div className={emailClasses}>
                    <label>Email Address</label>
                    <input className='form-control' type='email' {...email} />
                    {email.touched && email.error && <p className='text-danger'>{email.error}</p>}
                </div>

                <button type='submit' className='btn btn-lg btn-block btn-default'>Login</button>
            </form>
        );
    }
};

LoginForm = reduxForm({
    form: 'login',
    fields: ['email'],
    // validate
})(LoginForm);

export default LoginForm
```

**Comment by mhssmnn** [comment]
Managed to reproduce. Turns out my shorthand tests weren't working at all... Thanks for the heads up!

**Comment by privard** [comment]
Glad I could help, thanks for addressing this so quickly!
